### ISSUE TITLE
There is a issue when running tensorflow-gpu 1.14

### ISSUE THREAD

**Issue by eblog** [utcs-scea/ava#45]
At ava/benchmark/tensorflow/python path, follow the steps with README.
link_lib.sh is:
#!/bin/bash

if [ -z "$AVA_ROOT" ]
then
    echo "AVA_ROOT is not set"
    exit
fi

BASEDIR=$(dirname "$0")

ln -s $AVA_ROOT/cava/cudart_nw/libguestlib.so $BASEDIR/libcuda.so.1
ln -s $AVA_ROOT/cava/cudart_nw/libguestlib.so $BASEDIR/libcudart.so.10.0
ln -s $AVA_ROOT/cava/cudart_nw/libguestlib.so $BASEDIR/libcudnn.so.7
ln -s $AVA_ROOT/cava/cudart_nw/libguestlib.so $BASEDIR/libcublas.so.10.0
ln -s $AVA_ROOT/cava/cudart_nw/libguestlib.so $BASEDIR/libcufft.so.10.0
ln -s $AVA_ROOT/cava/cudart_nw/libguestlib.so $BASEDIR/libcurand.so.10.0
ln -s $AVA_ROOT/cava/cudart_nw/libguestlib.so $BASEDIR/libcusolver.so.10.0
ln -s $AVA_ROOT/cava/cudart_nw/libguestlib.so $BASEDIR/libcusparse.so.10.0

When I run:
LD_LIBRARY_PATH=util python3.6 test.py
I will see the following error log：
python3.6: cudart_nw_guestlib.c:21678: cuGetExportTable: Assertion `Unsupported API function: cuGetExportTable' failed.
By looking at the code, I found that this API is not supported on cava, my question is whether this interface is not implemented, is it not supported by cava or is it not implemented for a while because it was not used before?

**Comment by yuhc** [comment]
Hi @eblog -

`cuGetExportTable` isn't supposed to be called. The error shows that the AvA's generated CUDA API stubs are not called correctly. Could you please run some quick checks:

1. Are you using the TensorFlow in https://github.com/yuhc/tensorflow-cudart-dynam ?
2. What's the CUDA version (and CUDA Compute Capability) used by your TensorFlow? It's very likely that your TensorFlow is using some CUDA rather than 10.0.
3. Which spec is being used?

I'm refactoring the master branch (at a slow pace) but the [TensorFlow spec](https://github.com/utcs-scea/ava/tree/master/cava/samples/tensorflow) should work.

**Comment by eblog** [comment]
Hi @yuhc 
Thanks for your reply, this has been solved.
The reason for this issue is that tensorflow uses cudart_static. https://github.com/yuhc/tensorflow-cudart-dynam  its worked with the demo.py in benchmark/tensorflow/demo.py.
I used TenSorFlow1.14 and CUDA 10.0, used cudart_nw spec with tensorflow.
However, I encountered a new issue while running tensorflow MINST,  cava cudnn API It will report an error："python: cudart_nw_guestlib.c:21226: cudnnConvolutionForward: Assertion `Cannot forge success without a success value for the type.' failed."
Is the issue because cudnn's API  cudnnConvolutionForward is asynchronous？ How to fix this issue？

Thanks
eblog

**Comment by yuhc** [comment]
Yes, an `ava_async` API would return a default success value to the user program. 

In r1.0 version, we only tested a few simple TensorFlow NN inference benchmarks against `cudart_nw` spec. It was a TODO at that time to support more complicated TensorFlow benchmarks which invokes more common cudnn APIs.

The mentioned issue can be fixed by https://github.com/utcs-scea/ava/blob/master/cava/samples/tensorflow/tf_opt.c#L135. Because there are quite a few bugs fixed over the time, I suggest use the latest specs in the master branch `cava/samples/tensorflow/*` and [here is the instruction](https://github.com/utcs-scea/ava-benchmarks/blob/master/tensorflow/python/README) to use the new specs (dump and opt).

**Comment by eblog** [comment]
Hi @yuhc
I used he latest specs in the master branch cava/samples/tensorflow/tf_dump.c, and compilation generated the file ava/install/tf_dump/bin/worker and ava/install/tf_dump/lib/libguestlib.so.
when I run ava-benchmarks/tensorflow/python/demo.py, I have a issue with it, tensorflow report: "tensorflow/stream_executor/platform/default/dso_loader.cc:53] Could not dlopen library 'libcuda.so.1'; dlerror: util/libcuda.so.1: undefined symbol: _ZNK6google8protobuf7Message11GetTypeNameB5cxx11Ev; LD_LIBRARY_PATH: util"
the util/link_lib.sh file set as follows：

#!/bin/bash

if [ -z "$AVA_ROOT" ]
then
    echo "AVA_ROOT is not set"
    exit
fi

BASEDIR=$(dirname "$0")

ln -s $AVA_ROOT/install/tf_dump/lib/libguestlib.so $BASEDIR/libcuda.so.1
ln -s $AVA_ROOT/install/tf_dump/lib/libguestlib.so $BASEDIR/libcudart.so.10.0
ln -s $AVA_ROOT/install/tf_dump/lib/libguestlib.so $BASEDIR/libcudnn.so.7
ln -s $AVA_ROOT/install/tf_dump/lib/libguestlib.so $BASEDIR/libcublas.so.10.0

In an attempt to fix this issue, I  apt autoremove libprotobuf-dev protobuf-compiler, then I recompiled the install the protobuf-3.9.0,  and some environment variables are set, but I found that the issue still exists.
tensorflow is : https://github.com/yuhc/tensorflow-cudart-dynam 

Have you ever had a similar issue？

Thanks

**Comment by yuhc** [comment]
My bad. The gRPC dependency should be removed in 996a434718d5b1b070d. I notice that you are compiling the spec with AvA 2.0 (master branch), aren't you? This reminds me of a few issues of using the TF spec.

1. AvA 2.0 uses boost asio to connect to the manager, while only a simple manager prototype is current working. (I can port or advise you to [port AvA 1.0's manager](https://github.com/utcs-scea/ava/blob/master/docs/virtualize_new_api.md#writing-ava-manager).)
2. I introduced a few optimizations to TF virtualization with hacks to both AvA backend and Cava, so the TF spec can't be compiled within AvA 1.0. (I can send you a spec with those changes reverted.)

Please just let me know which is better for you so that I can schedule some time to resolve that first. (Both are on my todo list but I'm having busy days 😢.)

**Comment by eblog** [comment]
Hi @yuhc
Thank you for your immediate reply.
I'm using AvA 2.0 (master branch) now, I compiled AVA r1.0 before(use cudart SPEC), but there a few issues when running MNIST with tensorflow-cudart-dynam, then you suggest that I use the AvA 2.0 (master branch), compiling TF spec with cmake and the libguestlib.so and worker Binary files can be generat, I notice that AvA 2.0, as you said, there is no manager_tcp  available calls worker Binary to work.
My main purpose is to do some experiments with AVA, for example, run the MNIST or resnet50 models at the remote with AVA. I'm glad to get your reply when I have issue.
If I want to run tensorflow with AVA, is it more appropriate to solve the remaining issue based on AvA 2.0?  Or which way can let you pay less time, I don't want to take up too much of your time by some issue I encounter.  

Thanks.

**Comment by yuhc** [comment]
Got it. Then I'll fix the manager tomorrow and write a short doc. Yea it's better and easier to just use AvA 2.0. 
Will get back to you soon. Thanks!

**Comment by yuhc** [comment]
Hi @eblog,

I've fixed the problem by PR #62. But due to the time limit, some manager configurations are hard-coded at this moment. There are a few things needed to fix by hand:

* CUDA version: in both `tf_dump.c` and `tf_opt.c`. CUDA 10.0 should work with the current spec.
* API server IP address: `worker/legacy/manager.cpp:77`. Change `0.0.0.0` to your remote server's IP.
* API server pool size: `worker/legacy/manager.cpp:17`.

README:

* cava/samples/tensorflow/README.md

Please let me know if AvA raises any error with your your benchmark (e.g. any APIs aren't annotated, or any race condition).

**Comment by eblog** [comment]
Hi @yuhc
I found in both tf_dump.c and tf_opt.c, its cuda version 10.1, if I use cuda 10.0, compiling TF spec will report some error about API not implement, so I use ”nvidia driver 450.80.02 / cuda 10.1 / cudnn7.6.5“ compiling TF spec and legacy_manager.
After compiling, according to README:cava/samples/tensorflow/README.md, I test ava-benchmarks/tensorflow/python/demo.py with tensorflow-cudart-dynam, its work normal, but I run other test case(eg:kmeans.py or random_forest.py), it will report a Segmentation fault error.
log file:

LD_LIBRARY_PATH=~/ava-build/install/tf_opt/lib/ python3 kmeans.py >> /home/test.log
Start batch processing thread
Connect target API server (0.0.0.0:4002) at 0.0.0.0:4002
2021-01-25 21:10:04.585075: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/usr/local/lib/python3.6/dist-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
2021-01-25 21:10:05.551665: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From kmeans.py:30: read_data_sets (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:260: maybe_download (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Please write your own downloading logic.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:262: extract_images (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:267: extract_labels (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.data to implement this functionality.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:110: dense_to_one_hot (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use tf.one_hot on tensors.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py:290: DataSet.__init__ (from tensorflow.contrib.learn.python.learn.datasets.mnist) is deprecated and will be removed in a future version.
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
WARNING:tensorflow:From kmeans.py:41: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/contrib/factorization/python/ops/clustering_ops.py:740: calling l2_normalize (from tensorflow.python.ops.nn_impl) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2021-01-25 21:10:06.443990: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2021-01-25 21:10:06.444894: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 21:10:06.446577: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:07.0
2021-01-25 21:10:06.446600: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2021-01-25 21:10:06.446629: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
2021-01-25 21:10:06.446644: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10
2021-01-25 21:10:06.446659: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10
2021-01-25 21:10:06.446675: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10
2021-01-25 21:10:06.446689: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10
2021-01-25 21:10:06.446704: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2021-01-25 21:10:06.446992: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 21:10:06.448837: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 21:10:06.450371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2021-01-25 21:10:06.461729: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2499995000 Hz
2021-01-25 21:10:06.465858: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x49430d0 executing computations on platform Host. Devices:
2021-01-25 21:10:06.465887: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2021-01-25 21:10:06.468454: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 21:10:06.470262: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x49a1a90 executing computations on platform CUDA. Devices:
2021-01-25 21:10:06.470283: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla T4, Compute Capability 7.5
2021-01-25 21:10:06.471600: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 21:10:06.473224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla T4 major: 7 minor: 5 memoryClockRate(GHz): 1.59
pciBusID: 0000:00:07.0
2021-01-25 21:10:06.473247: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.1
2021-01-25 21:10:06.473256: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
2021-01-25 21:10:06.473264: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10
2021-01-25 21:10:06.473271: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10
2021-01-25 21:10:06.473279: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10
2021-01-25 21:10:06.473287: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10
2021-01-25 21:10:06.473295: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2021-01-25 21:10:06.473576: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 21:10:06.475471: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 21:10:06.477048: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2021-01-25 21:10:06.477290: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-25 21:10:06.477299: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2021-01-25 21:10:06.477305: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2021-01-25 21:10:06.477673: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 21:10:06.479613: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2021-01-25 21:10:06.481268: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 12377 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:00:07.0, compute capability: 7.5)
2021-01-25 21:10:06.658679: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
Segmentation fault

**Comment by yuhc** [comment]
kmeans.py works fine on my server. Are you using the CUDA dumps generated by running `demo.py` to run `kmeans.py`? Because the CUDA kernels touched by `kmeans.py` is a superset of those by `demo.py`, the proper way is to use `kmeans.py`'s dumps for both `kmeans.py` and `demo.py`, or generate a set of dumps for every benchmark.

**Comment by eblog** [comment]
Hi @yuhc
It was caused by the wrong method I used, all *. ava files in my directory are demo.py generat, according to the method you said, it (demo.py, kmeans.py, nearest_neighbor.py linear_regression.py, random_forest.py) is running normally at present.

I also tested resnet50 by the same method:

1. ./install/bin/legacy_manager install/tf_dump/bin/worker
2. LD_LIBRARY_PATH=~/ava-build/install/tf_dump/lib/ python3 tf_cnn_benchmarks.py --batch_size=32 --model=resnet50
3. cp /tmp/*.ava /cuda_dumps
4. ./install/bin/legacy_manager install/tf_opt/bin/worker
5. LD_LIBRARY_PATH=~/ava-build/install/tf_opt/lib/ python3 tf_cnn_benchmarks.py --batch_size=32 --model=resnet50

Tensorflow report an error: cudnnBatchNormalizationForwardTraining is not implemented.
To solve this issue, how can I know the specific logic of the API if I want to implement the API through AVA, I have implemented some new cuda APIs with reference to other APIs you have implemented before(AVA r1.0), but I don't know how to ensure that what I have implemented is correct, is there a specific debugging method? If there is a way to ensure that the CUDA API implemented is correct, I can open source the API I implemented.

Tensorflow log:
I0126 11:16:35.401717 139972289337152 session_manager.py:500] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0126 11:16:35.452189 139972289337152 session_manager.py:502] Done running local_init_op.
Running warm up
2021-01-26 11:16:36.937282: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10
2021-01-26 11:16:36.957313: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
cudnnBatchNormalizationForwardTraining is not implemented
Fatal Python error: Aborted

Thread 0x00007f4dd6959740 (most recent call first):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1429 in _call_tf_sessionrun
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1341 in _run_fn
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1356 in _do_call
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350 in _do_run
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1173 in _run
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 950 in run
  File "/home/benchmark/tensorflow/python/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 870 in benchmark_one_step
  File "/home/benchmark/tensorflow/python/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2433 in benchmark_with_session
  File "/home/benchmark/tensorflow/python/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2295 in _benchmark_graph
  File "/home/benchmark/tensorflow/python/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 2088 in _benchmark_train
  File "/home/benchmark/tensorflow/python/benchmarks/scripts/tf_cnn_benchmarks/benchmark_cnn.py", line 1883 in run
  File "benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 68 in main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251 in _run_main
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303 in run
  File "benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py", line 73 in <module>
Aborted


Thanks

**Comment by yuhc** [comment]
Sadly for supporting TensorFlow, we currently learn which APIs to annotate from crash. If I'm not wrong, are you running [https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks](tf_cnn_benchmarks)? I can try to make it work--it shall cost me much less time as I'm more experienced in this.

**Comment by eblog** [comment]
yes, I'm running tensorflow test with: https://github.com/tensorflow/benchmarks/tree/master/scripts/tf_cnn_benchmarks.
Thank you for helping me fix this issue.  I also want to learn how to make AVA support more CUDA application scenarios. 
It would be great if you had some advice or experience to share.

thanks.

**Comment by yuhc** [comment]
For normal CUDA applications, we usually use ltrace to trace the library calls and find which CUDA APIs are called.
For TensorFlow backed by AvA, there's too much noise in the ltrace output, so we just learn from crashes.

In this example of supporting tf_cnn_benchmarks, I annotated `cudnnBatchNormalizationForwardTraining` (and `cudnnBatchNormalizationForwardTrainingEx` by the way) first, ran the benchmark again and got the next API to annotate.
The commit is at ce34d4bb6d3e1b586e0c19bcd6c0173f7d33eea5 in PR #65.
